#FROM centos:centos7
FROM debian:jessie
MAINTAINER Michael Hoffmann

# Install NGINX
#RUN yum -y update; yum clean all
#RUN yum -y install http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm; yum -y makecache
#RUN yum -y install nginx-1.8.0

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    wget \
    curl \
    nginx \
    zip \
    openssh-client \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Remove default files we don't need
#RUN rm /etc/nginx/conf.d/default.conf
#RUN rm /etc/nginx/conf.d/example_ssl.conf

# Add default configuration
#COPY conf/jenkins.conf /etc/nginx/conf.d/jenkins.conf
#COPY conf/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8000

CMD ["nginx"]
